name: Pruebas Cypress
on:
  push:
    branches: 
      - main
  pull_request: 
    branches:
      - main

  workflow_dispatch: 

jobs:
  cypress-run:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20'

      - name: Remove node_modules and package-lock.json
        run: |
          if (Test-Path node_modules) { Remove-Item -Recurse -Force node_modules }
          if (Test-Path package-lock.json) { Remove-Item -Force package-lock.json }
        working-directory: ./sitio_pruebas
